### ISSUE TITLE
FEA work

### ISSUE THREAD

**Issue by spolanski** [spolanski/CoFEA#51]
# Contribution guide
If you wish to contribute to the CoFEA Initiative, you can choose one of the benchmarks which you will find below or provide your own example. Then please do following:
1. Make a comment in this issue that you are going to work on it
2. [Create a new benchmark issue](https://github.com/spolanski/CoFEA/issues/new/choose)

# Benchmarks
The following list contains a possible set of benchmarks which can be used to evaluate the performance of codes. If you want to start working on any of below, please create appropriate Github issue as described at the top of this issue.

- [ ] 01-LE10-Thick-Plate #23 
- [ ] 02-Cooks-membrane #25 
- [ ] 03-Hertz-contact #52
- [ ] 04-eliptic-membrane #56 
- [ ] 05-hemispherical-shell-point-load #57
- [ ] 06-plastic-strain-test #58
- [ ] 07-Raasch-shell-challenge #59
- [ ]  [LE2 Shell](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf02.html)
- [ ]  [LE5 Shell](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf05.html)
- [ ]  [LE6 Shell](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf06.html)
- [ ]  [Spring model](https://www.nafems.org/downloads/dropbox/resource_center/benchmark/bm_jul_19_4.pdf)
- [ ]  [3DNLG-1 Shell / Beam](http://wufengyun.com:888/v6.14/books/bmk/ch04s10anf84.html)
- [ ]  [3DNLG-2 Shell](http://wufengyun.com:888/v6.14/books/bmk/ch04s10anf85.html)
- [ ]  [3DNLG-10 Shell](http://wufengyun.com:888/v6.14/books/bmk/ch04s10anf93.html)
- [ ]  [Solid / Shell / Axisymmetric (Dynamic)](https://inis.iaea.org/collection/NCLCollectionStore/_Public/25/018/25018346.pdf?r=1)
- [ ]  [LE04 Axisymmetric Shell (Beam in 2D)](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf04.html)
- [ ]  [LE07 Axisymmetric Shell (Beam in 2D)](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf07.html)
- [ ]  [LE08 Axisymmetric Shell (Beam in 2D)](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf08.html)
- [ ]  [LE09 Axisymmetric Shell (Beam in 2D)](http://wufengyun.com:888/v6.14/books/bmk/ch04s02anf09.html)
